name = "compositional-protocol-proof"
version = "0.1.0"
defaultTargets = ["CompositionalProtocolProof", "CMCM"]

# [[require]]
# name = "Hammer"
# git = "https://github.com/JOSHCLUNE/LeanHammer"
# rev = "temp-v4.21.0-rc3"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc3"

# [[require]]
# name = "Canonical"
# scope = "chasenorman"
# rev = "v4.22.0"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "CompositionalProtocolProof"

[[lean_lib]]
name = "CMCM"

[[lean_lib]]
name = "Herd"
