name = "compositional-protocol-proof"
version = "0.1.0"
defaultTargets = ["compositional-protocol-proof"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "CompositionalProtocolProof"

[[lean_exe]]
name = "compositional-protocol-proof"
root = "Main"
