import CompositionalProtocolProof.CompoundSWMR
import CompositionalProtocolProof.CompoundProtocol

import CompositionalProtocolProof.CompositionalProof.Lemma6GlobalWriteDowngrade
import CompositionalProtocolProof.CompositionalProof.Lemma7GlobalReadDowngrade
