import CompositionalProtocolProof.CompoundSWMR
import CompositionalProtocolProof.CompoundProtocol

import CompositionalProtocolProof.CompositionalProof.ProofBasic
import CompositionalProtocolProof.CompositionalProof.Lemma4ClusterRequest

variable (n : Nat)

-- ∀ Cluster Dir & Global Cache Events, CompoundSWMR holds iff ∀ Cluster Cache Event, Compound SWMR holds
/- TODO: Show that the Prop `CompoundSWMR` holds iff for all cluster cache events, `CompoundSWMR` holds
  1. Fwd (MP) case: Use Request and Shim Axioms to show we can go from Cluster Cache Events to `CompoundSWMR`
  2. Reverse (MPR) case: Let there be an arbitrary ClusterCacheEvent event `e` in Behaviour `b`.
    a. By Request and Shim axioms, `e` may:
      i. produce additional Cluster Directory Events and Global Cache Events,
        that by `CompoundSWMR` still enforce `CompoundSWMR`.
      ii. If they produce none, then the system is still in Compound SWMR.
-/

/- [TODO-NOTE] Remember to add axioms/assumptions that all Directory Events are caused by Cache Events (by Axiom 6),
all Global Cache Events are caused by Cluster Directory Events (by Shim Axiom 15) -/

/-- Lemma 8a. Show it's enough to consider that Events originating from Cluster Cache Events satsify compound SWMR. -/
lemma CompoundProtocol.compound_swmr_iff_cluster_requests_satsify_compound_swmr
  (b : Behaviour n) (init : InitialSystemState n) (cmp_protocol : CompoundProtocol n)
  : CompoundSWMR.wrapper n b init ↔ (
    ∀ e ∈ b,
    (∀ e_cdir ∈ b, e_cdir.isClusterDir → b.clusterDirFinishBeforeUnrelated n init e e_cdir → CompoundSWMR.stateAfterClusterDirEventLeGlobalCache n b init e_cdir) →
    (∀ e_gcache ∈ b, e_gcache.isGlobalCache → b.globalCacheFinishBeforeUnrelated n init e e_gcache → CompoundSWMR.stateAfterClusterDirEventLeGlobalCache' n b init e_gcache) →
      b.allClusterEventCorrespondingDirEventSatisfyCompoundSWMR n init e) := by
  apply Iff.intro
  . case mp =>
    intro cmp_swmr
    intro e he_in_b
    /- Strategy:
    Cases on `e`'s request and state it's made on.
    Use the corresponding Inductive Constructor to match each case in `e`.
    Using `cmp_swmr` wrapper will make this trivial
    -/
    sorry
  . case mpr =>
    intro he_in_b_satisfy_cmp_swmr
    simp[CompoundSWMR.wrapper]
    intro e_cdir_or_gcache he_in_b he_cluster_dir_or_global_cache
    -- simp[CompoundSWMR]
    -- let cluster_cache_event : Event n :=
    /- Strategy:
    1. Use additional axioms to say that cluster directory / global cache events must have come from a cluster request originally,
    through some transitive chain. Apply the axioms to `e_cdir_or_gcache` to get a Cluster Cache Event `e_cluster_cache`.
    2. Then use `he_in_b_satisfy_cmp_swmr` to state that `e_cluster_cache` encapsulates a corresponding
    -/
    sorry

-- ∀ cmpProtocol, CompoundSWMR holds
/- TODO: State that Cluster-Cache-Events enforce Compound SWMR
1. consider set of events at a cluster cache entry
  a. In the empty case, Compound SWMR is maintained (assuming initial state is Compound SWMR)
  b. In the multiple case, map the set to the equivalent list of events at the cache entry.
2. Multiple case:
  a. induct on the list; by Lemma 4, we know all Cache Request Events leave the protocol in Compound SWMR;
  b. in the inductive step case `cons`, apply the induction hypothesis.
-/

-- [NOTE] is it worth considering any sequence of events? The generic `∀ e ∈ b, satisfies cmp-swmr` sounds like it's enough?
-- might be safer to just do it. i.e. include another lemma below Lemma 8b, to say for all events in b, they preserve SWMR

/-- Lemma 8b. Show that events generated by Cluster Cache Events all statisfy Compound SWMR.
(i.e. Cluster Cache Events satisfy Compound SWMR) -/
lemma CompoundProtocol.compound_swmr_holds
  (b : Behaviour n) (init : InitialSystemState n) (cmp_protocol : CompoundProtocol n)
  : CompoundSWMR.wrapper n b init := by
  rw[CompoundProtocol.compound_swmr_iff_cluster_requests_satsify_compound_swmr n b init cmp_protocol]
  intro e he_in_b
  intro hall_cdir_sat_cmp_swmr
  intro hall_gcache_sat_cmp_swmr
  -- intro e_cdir he_cdir_in_b he_cdir_is_cluster_dir he_cdir_finish_before_e he_cdir_sat_cmp_swmr
  -- intro e_gcache e_gcache_in_b he_gcache_is_global_cache he_gcache_finish_before_e he_gcache_sat_cmp_swmr
  apply Behaviour.cluster_request_enforces_compound_swmr n b init cmp_protocol e he_in_b
  . case hpred_cdir_cmp_swmr => exact hall_cdir_sat_cmp_swmr
  . case hpred_gcache_cmp_swmr => exact hall_gcache_sat_cmp_swmr
